library(Seurat)
library(SeuratData)
library(ggplot2)
library(patchwork)
library(dplyr)
library(rhdf5)
library(Matrix)
library(sctransform)
library(plyr)
library(gridExtra)
library(magrittr)
library(tidyr)
library(raster)
library(OpenImageR)
library(ggpubr)
library(grid)
library(wesanderson)

dir <- "C:/Users/EDIC-THINKPAD/Desktop/FFPEs/FFPE-2/cell_annotation"  
setwd("C:/Users/EDIC-THINKPAD/Desktop/FFPEs/FFPE-2/cell_annotation")

#change filename1 to name of txt file you want to load
data1 <- read.table("annotation.tsv", header = TRUE, sep = "\t",  row.names = 1)

levels(data1$Name)

data1[] <- lapply(data1, gsub, pattern='<=', replacement='')

data1$Sox2<- as.numeric(data1[])

cols.num = -c(1,2)
data1[cols.num] <- sapply(data1[cols.num],as.numeric)
data1[cols.num] <- sapply(data1[cols.num],scale)


longdata10 <- gather(data = data1, key = Class, value = Abundance, -c(1:2))

levels(longdata10$Name)

longdata10$Abundance <- as.numeric(longdata10$Abundance)

longdata10$Name <- factor(longdata10$Name,levels = c("TEGLU1",
                                                     "TEGLU3",
                                                     "TEGLU2",
                                                     "TEGLU20",
                                                     "TEGLU11",
                                                     "TEGLU12",
                                                     "TEGLU10",
                                                     "TEGLU9",
                                                     "TEGLU8",
                                                     "TEGLU7",
                                                     "TEGLU6",
                                                     "TEGLU13",
                                                     "TEGLU14",
                                                     "TEGLU5",
                                                     "TEGLU16",
                                                     "TEGLU15",
                                                     "TEGLU17",
                                                     "TEGLU18",
                                                     "TEGLU19",
                                                     "TEGLU22",
                                                     "TEGLU21",
                                                     "TEGLU4",
                                                     "TEGLU24",
                                                     "TEGLU23",
                                                     "DGGRC1",
                                                     "DGGRC2",
                                                     "MSN1",
                                                     "MSN2",
                                                     "MSN3",
                                                     "MSN4",
                                                     "MSN5",
                                                     "MSN6",
                                                     "DETPH",
                                                     "DGNBL2",
                                                     "DGNBL1",
                                                     "SZNBL",
                                                     "OBNBL3",
                                                     "OBINH1",
                                                     "OBINH5",
                                                     "OBINH2",
                                                     "OBINH3",
                                                     "OBINH4",
                                                     "OBNBL4",
                                                     "OBNBL5",
                                                     "OBDOP",
                                                     "OBINH6",
                                                     "DEINH1",
                                                     "DEINH2",
                                                     "TEINH17",
                                                     "TEINH18",
                                                     "TEINH19",
                                                     "TEINH21",
                                                     "TEINH16",
                                                     "TEINH15",
                                                     "TEINH14",
                                                     "TEINH20",
                                                     "TEINH13",
                                                     "TEINH12",
                                                     "TEINH9",
                                                     "TEINH10",
                                                     "TEINH11",
                                                     "TEINH4",
                                                     "TEINH5",
                                                     "TEINH8",
                                                     "TEINH7",
                                                     "TEINH6",
                                                     "TECHO",
                                                     "DECHO1",
                                                     "HBCHO4",
                                                     "HBCHO3",
                                                     "HBADR",
                                                     "HBNOR",
                                                     "HYPEP7",
                                                     "HYPEP6",
                                                     "MEGLU14",
                                                     "MBDOP1",
                                                     "MBDOP2",
                                                     "HBSER1",
                                                     "HBSER2",
                                                     "HBSER3",
                                                     "HBSER5",
                                                     "HBSER4",
                                                     "TEINH3",
                                                     "TEINH2",
                                                     "DEINH4",
                                                     "DEINH5",
                                                     "HYPEP3",
                                                     "HYPEP1",
                                                     "HYPEP2",
                                                     "MEINH14",
                                                     "DEINH6",
                                                     "DEINH8",
                                                     "DEINH7",
                                                     "HYPEP5",
                                                     "HYPEP4",
                                                     "HYPEP8",
                                                     "SCINH11",
                                                     "SCINH10",
                                                     "SCINH9",
                                                     "SCINH8",
                                                     "SCINH7",
                                                     "SCINH6",
                                                     "SCINH5",
                                                     "SCINH4",
                                                     "SCINH3",
                                                     "HBINH9",
                                                     "SCINH2",
                                                     "SCGLU1",
                                                     "SCGLU2",
                                                     "SCGLU3",
                                                     "SCGLU4",
                                                     "SCGLU5",
                                                     "SCGLU6",
                                                     "SCGLU7",
                                                     "SCGLU8",
                                                     "SCGLU9",
                                                     "SCGLU10",
                                                     "HBGLU10",
                                                     "HBGLU3",
                                                     "HBGLU2",
                                                     "MEGLU2",
                                                     "MEGLU3",
                                                     "DEGLU5",
                                                     "MEGLU1",
                                                     "MEGLU7",
                                                     "MEGLU8",
                                                     "MEGLU9",
                                                     "MEGLU10",
                                                     "MEGLU11",
                                                     "MBCHO1",
                                                     "MEGLU6",
                                                     "MEGLU5",
                                                     "MEGLU4",
                                                     "CR",
                                                     "DECHO2",
                                                     "HBGLU1",
                                                     "DEGLU1",
                                                     "DEGLU2",
                                                     "DEGLU3",
                                                     "DEGLU4",
                                                     "MEINH12",
                                                     "MEINH11",
                                                     "MEINH10",
                                                     "MEINH9",
                                                     "MEINH5",
                                                     "MEINH6",
                                                     "MEINH7",
                                                     "MEINH4",
                                                     "MEINH3",
                                                     "HBINH5",
                                                     "MEINH2",
                                                     "DEINH3",
                                                     "TEINH1",
                                                     "MEINH13",
                                                     "MEINH8",
                                                     "HBINH1",
                                                     "HBINH3",
                                                     "HBINH4",
                                                     "HBINH6",
                                                     "HBINH2",
                                                     "HBCHO1",
                                                     "HBCHO2",
                                                     "HBGLU4",
                                                     "HBGLU5",
                                                     "HBGLU6",
                                                     "HBGLU7",
                                                     "HBGLU8",
                                                     "HBGLU9",
                                                     "HBINH7",
                                                     "HBINH8",
                                                     "SCINH1",
                                                     "CBINH2",
                                                     "MEINH1",
                                                     "CBINH1",
                                                     "CBPC",
                                                     "CBGRC",
                                                     "CBNBL2",
                                                     "CBNBL1",
                                                     "SEPNBL",
                                                     "OBNBL1",
                                                     "OBNBL2",
                                                     "ENT1",
                                                     "ENT2",
                                                     "ENT3",
                                                     "ENT4",
                                                     "ENT5",
                                                     "ENT6",
                                                     "ENT7",
                                                     "ENT8",
                                                     "ENT9",
                                                     "SYNOR1",
                                                     "SYNOR2",
                                                     "SYNOR3",
                                                     "SYNOR4",
                                                     "SYNOR5",
                                                     "SYCHO2",
                                                     "SYCHO1",
                                                     "PSPEP8",
                                                     "PSPEP7",
                                                     "PSPEP6",
                                                     "PSPEP5",
                                                     "PSPEP2",
                                                     "PSPEP4",
                                                     "PSPEP3",
                                                     "PSPEP1",
                                                     "PSNF3",
                                                     "PSNF2",
                                                     "PSNF1",
                                                     "PSNP1",
                                                     "PSNP2",
                                                     "PSNP3",
                                                     "PSNP4",
                                                     "PSNP5",
                                                     "PSNP6",
                                                     "COP1",
                                                     "COP2",
                                                     "NFOL2",
                                                     "NFOL1",
                                                     "MFOL2",
                                                     "MFOL1",
                                                     "MOL1",
                                                     "MOL2",
                                                     "MOL3",
                                                     "CHOR",
                                                     "HYPEN",
                                                     "EPSC",
                                                     "EPEN",
                                                     "EPMB",
                                                     "RGDG",
                                                     "RGSZ",
                                                     "ACTE1",
                                                     "ACTE2",
                                                     "ACOB",
                                                     "ACNT1",
                                                     "ACNT2",
                                                     "ACMB",
                                                     "ACBG",
                                                     "OEC",
                                                     "OPC",
                                                     "SCHW",
                                                     "SATG2",
                                                     "SATG1",
                                                     "ENTG1",
                                                     "ENTG2",
                                                     "ENTG3",
                                                     "ENTG4",
                                                     "ENTG5",
                                                     "ENTG6",
                                                     "ENTG7",
                                                     "ENMFB",
                                                     "ABC",
                                                     "VLMC2",
                                                     "VLMC1",
                                                     "VECA",
                                                     "PER3",
                                                     "VSMCA",
                                                     "PER1",
                                                     "PER2",
                                                     "VECC",
                                                     "VECV",
                                                     "PVM1",
                                                     "PVM2",
                                                     "MGL3",
                                                     "MGL2",
                                                     "MGL1"
                                                     
                                       
                                       
))

longdata10$Class <- factor(longdata10$Class,levels = c("Nnat",
                                                       "Map1b",
                                                       "Tubb3",
                                                       "Stmn2",
                                                       "Dpysl3",
                                                       "Tuba1a",
                                                       "Ina",
                                                       "Elavl3",
                                                       "Mapt",
                                                       "Malat1",
                                                       "Col3a1",
                                                       "Dkk2",
                                                       "Col1a2",
                                                       "Col1a1",
                                                       "Meg3",
                                                       "Nfib",
                                                       "Cdkn1c",
                                                       "Igfbp5",
                                                       "Hmga2",
                                                       "Prrx1",
                                                       "Mest",
                                                       "Igf2",
                                                       "H19",
                                                       "Hist1h2ao",
                                                       "Hist1h2ap",
                                                       "Chd7",
                                                       "Pea15a",
                                                       "Zic1",
                                                       "Hes5",
                                                       "Ttyh1",
                                                       "Sox9",
                                                       "Fabp7",
                                                       "Sox2"
                                                     
                                                       
  
))  

levels(longdata10$Class)
ggplot(longdata10, aes(Name, Class)) + 
  geom_tile(aes(fill = Abundance), color = "white") + scale_fill_gradientn(colors= c("white", "darkblue")) +
  theme(axis.title=element_blank(),
        legend.position = "none",
        axis.text.x = element_blank())

